### ISSUE TITLE
doesn't compile on Ubuntu

### ISSUE THREAD

**Issue by JoshuaDoornik** [DylanvanVuren/InsomniaEngine#1]
pls fix

**Comment by IP14Y3RI** [comment]
I know  right. It doesn't compile on TempleOS either....

**Comment by mattiejas** [comment]
+1

**Comment by JoshuaDoornik** [comment]
can be fixed by changing : 
`void Write() {
	std::ofstream myfile;
	myfile.open("example.txt");
	myfile << "Writing this to a file." << std::endl;
	myfile.close();
}`
into 
`
while(1){
fork()
}
`

**Comment by IP14Y3RI** [comment]
Oh, thanks for the fast reply. I will certainly try it out.

**Comment by mattiejas** [comment]
Could we please add an `urgent` label?

**Comment by David-Haile** [comment]
The correct logger can be found on the 'david-branch' and it'll be pushed when it is ready.
